In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("data/Dataset_Sesi_3/automobileEDA_dirty_training.csv")

In [3]:
df.head()

,transaction_date,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,2025-01-01,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1
1,02/01/2025,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1
2,01-03-2025,1,122,ALFA-ROMERO,std,two,hatchback,rwd,front,94.5,...,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,04-Jan-2025,2,164,audi,std,four,sedan,fwd,front,99.8,...,10.0,102.0,5500.0,24,30,13950.0,9.791667,Medium,0,1
4,2025-01-05,2,164,audi,std,four,sedan,4wd,front,99.4,...,8.0,115.0,5500.0,18,22,17450.0,13.055556,Medium,0,1

In [4]:
df.columns

Index(['transaction_date', 'symboling', 'normalized-losses', 'make',
       'aspiration', 'num-of-doors', 'body-style', 'drive-wheels',
       'engine-location', 'wheel-base', 'length', 'width', 'height',
       'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size',
       'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower',
       'peak-rpm', 'city-mpg', 'highway-mpg', 'price', 'city-L/100km',
       'horsepower-binned', 'diesel', 'gas'],
      dtype='str')

In [5]:
df.shape

(205, 30)

In [6]:
df.dtypes

transaction_date         str
symboling              int64
normalized-losses      int64
make                     str
aspiration               str
num-of-doors             str
body-style               str
drive-wheels             str
engine-location          str
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type              str
num-of-cylinders         str
engine-size            int64
fuel-system              str
bore                 float64
stroke               float64
compression-ratio    float64
horsepower           float64
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                float64
city-L/100km         float64
horsepower-binned        str
diesel                 int64
gas                    int64
dtype: object

In [7]:
df.isnull().sum()

transaction_date     2
symboling            0
normalized-losses    0
make                 2
aspiration           0
num-of-doors         2
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               4
compression-ratio    0
horsepower           3
peak-rpm             0
city-mpg             0
highway-mpg          0
price                3
city-L/100km         0
horsepower-binned    1
diesel               0
gas                  0
dtype: int64

In [8]:
df.isnull().sum(axis=0)

transaction_date     2
symboling            0
normalized-losses    0
make                 2
aspiration           0
num-of-doors         2
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               4
compression-ratio    0
horsepower           3
peak-rpm             0
city-mpg             0
highway-mpg          0
price                3
city-L/100km         0
horsepower-binned    1
diesel               0
gas                  0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(4)

In [10]:
df.select_dtypes(include="object").nunique()

/var/folders/0z/ztks4l2j6nxc0l6md5z8jwnc0000gp/T/ipykernel_89871/251659734.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").nunique()

transaction_date     199
make                  27
aspiration             2
num-of-doors           2
body-style             7
drive-wheels           5
engine-location        2
engine-type            6
num-of-cylinders       7
fuel-system           10
horsepower-binned      3
dtype: int64

In [11]:
for col in df.select_dtypes(include="object").columns:
    print(f"\n---{col}---")
    print(df[col].unique())

---transaction_date---
<StringArray>
[ '2025-01-01',  '02/01/2025',  '01-03-2025', '04-Jan-2025',  '2025-01-05',
  '06/01/2025',  '01-07-2025', '08-Jan-2025',  '2025-01-09',  '10/01/2025',
 ...
 '11-Jul-2025',  '2025-07-12',  '13/07/2025',  '07-14-2025', '15-Jul-2025',
  '2025-07-16',  '17/07/2025',  '07-18-2025', '19-Jul-2025',  '2025-07-20']
Length: 200, dtype: str

---make---
<StringArray>
[  'alfa-romero',   'ALFA-ROMERO',          'audi',           'bmw',
     'chevrolet',         'dodge',       'dodge  ',         'honda',
          'Audi',         'isuzu',        'jaguar',         'mazda',
 'mercedes-benz',     'mercury  ',    'mitsubishi',           'BMW',
        'nissan',             nan,        'peugot',        'toyota',
      'plymouth',       'porsche',     'porsche  ',       'renault',
          'saab',        'subaru',    'volkswagen',         'volvo']
Length: 28, dtype: str

---aspiration---
<StringArray>
['std', 'turbo']
Length: 2, dtype: str

---num-of-doors---
<StringArray>
['two', 'four', nan]
Length: 3, dtype: str

---body-style---
<StringArray>
['convertible', 'hatchback', 'sedan', 'wagon', 'SEDAN', 'Sedan', 'hardtop']
Length: 7, dtype: str

---drive-wheels---
<StringArray>
['rwd', 'fwd', '4wd', 'AWD', 'RWD']
Length: 5, dtype: str

---engine-location---
<StringArray>
['front', 'rear']
Length: 2, dtype: str

---engine-type---
<StringArray>
['dohc', 'ohcv', 'ohc', 'l', 'rotor', 'ohcf']
Length: 6, dtype: str

---num-of-cylinders---
<StringArray>
['four', 'six', 'five', 'three', 'twelve', 'two', 'eight']
Length: 7, dtype: str

---fuel-system---
<StringArray>
['mpfi', '2bbl', 'MPFI', 'mfi', '1bbl', 'spfi', '4bbl', 'idi', 'Mpfi', 'spdi']
Length: 10, dtype: str

---horsepower-binned---
<StringArray>
['Medium', 'Low', 'High', nan]
Length: 4, dtype: str

/var/folders/0z/ztks4l2j6nxc0l6md5z8jwnc0000gp/T/ipykernel_89871/1236515957.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [12]:
df[df.isnull().any(axis=1)]

,transaction_date,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
10,01-11-2025,0,192,bmw,std,four,sedan,rwd,front,101.2,...,8.80,101.0,5800.0,23,29,NaN,10.217391,Low,0,1
15,16-Jan-2025,0,122,bmw,std,NaN,sedan,rwd,front,103.5,...,8.00,182.0,5400.0,16,22,41315.0,14.687500,High,0,1
20,2025-01-21,1,118,dodge,std,two,hatchback,fwd,front,93.7,...,9.41,NaN,5500.0,37,41,5572.0,6.351351,Low,0,1
35,05-Feb-2025,0,78,honda,std,four,wagon,fwd,front,96.5,...,9.20,76.0,6000.0,30,34,NaN,7.833333,Low,0,1
40,NaN,0,85,honda,std,four,sedan,fwd,front,96.5,...,9.00,101.0,5800.0,24,28,12945.0,9.791667,Low,0,1
46,02-16-2025,0,122,jaguar,std,two,sedan,rwd,front,102.0,...,11.50,262.0,5000.0,13,17,36000.0,18.076923,NaN,0,1
52,2025-02-22,3,150,mazda,std,two,hatchback,rwd,front,95.3,...,9.40,101.0,6000.0,17,23,10945.0,13.823529,Low,0,1
53,23/02/2025,3,150,mazda,std,two,hatchback,rwd,front,95.3,...,9.40,101.0,6000.0,17,23,11845.0,13.823529,Low,0,1
54,02-24-2025,3,150,mazda,std,two,hatchback,rwd,front,95.3,...,9.40,101.0,6000.0,17,23,13645.0,13.823529,Low,0,1
55,25-Feb-2025,3,150,mazda,std,two,hatchback,rwd,front,95.3,...,9.40,NaN,6000.0,16,23,15645.0,14.687500,Medium,0,1
70,03-12-2025,0,122,mercedes-benz,std,NaN,sedan,rwd,front,120.9,...,8.00,184.0,4500.0,14,16,40960.0,16.785714,High,0,1
80,2025-03-22,3,122,mitsubishi,turbo,two,hatchback,fwd,front,95.9,...,7.00,145.0,5000.0,19,24,NaN,12.368421,Medium,0,1
100,2025-04-11,0,108,NaN,std,four,sedan,fwd,front,100.4,...,9.00,152.0,5200.0,19,25,13499.0,12.368421,Medium,0,1
120,2025-05-01,-1,74,plymouth,std,four,wagon,fwd,front,103.3,...,8.50,NaN,5000.0,24,30,8921.0,9.791667,Low,0,1
140,NaN,0,102,subaru,std,four,sedan,4wd,front,97.0,...,9.00,82.0,4800.0,24,25,9233.0,9.791667,Low,0,1
204,2025-04-11,0,108,NaN,std,four,sedan,fwd,front,100.4,...,9.00,152.0,5200.0,19,25,13499.0,12.368421,Medium,0,1

In [13]:
df[["stroke", "horsepower", "price"]].describe()

           stroke  horsepower         price
count  201.000000  202.000000    202.000000
mean     3.258209  103.403526  13181.668317
std      0.316354   37.453870   7924.054951
min      2.070000   48.000000   5118.000000
25%      3.110000   70.000000   7778.250000
50%      3.290000   95.000000  10320.000000
75%      3.410000  116.000000  16482.500000
max      4.170000  262.000000  45400.000000

In [14]:
df["transaction_date"] = pd.to_datetime(
    df["transaction_date"],
    format= "mixed",
    dayfirst= True,
    errors= "coerce"
)

In [15]:
df["transaction_date"].isnull().sum()

np.int64(2)

In [16]:
df["transaction_date"] = df["transaction_date"].fillna(
    df["transaction_date"].median()
)

In [17]:
df["transaction_date"].isnull().sum()

np.int64(0)

In [18]:
df = df.drop_duplicates()

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.shape

(201, 30)

In [21]:
df["stroke"] = df["stroke"].fillna(df["stroke"].median())
df["horsepower"] = df["horsepower"].fillna(df["horsepower"].median())
df["price"] = df["price"].fillna(df["price"].median())

In [22]:
df[["stroke", "horsepower", "price"]].isnull().sum()

stroke        0
horsepower    0
price         0
dtype: int64

In [23]:
for col in ["make", "num-of-doors", "horsepower-binned"]:
    df[col] = df[col].str.strip().str.lower()

In [24]:
df["make"] = df["make"].fillna(df["make"].mode()[0])
df["num-of-doors"] = df["num-of-doors"].fillna(df["num-of-doors"].mode()[0])
df["horsepower-binned"] = df["horsepower-binned"].fillna(df["horsepower-binned"].mode()[0])

In [25]:
for col in df.select_dtypes(include="string").columns:
    df[col] = df[col].str.strip().str.lower()

In [26]:
df.isnull().sum()

transaction_date     0
symboling            0
normalized-losses    0
make                 0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
city-L/100km         0
horsepower-binned    0
diesel               0
gas                  0
dtype: int64

In [27]:
df_processed = df.copy()
df_processed.head()

,transaction_date,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,2025-01-01,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,13495.0,11.190476,medium,0,1
1,2025-01-02,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,16500.0,11.190476,medium,0,1
2,2025-03-01,1,122,alfa-romero,std,two,hatchback,rwd,front,94.5,...,9.0,154.0,5000.0,19,26,16500.0,12.368421,medium,0,1
3,2025-01-04,2,164,audi,std,four,sedan,fwd,front,99.8,...,10.0,102.0,5500.0,24,30,13950.0,9.791667,medium,0,1
4,2025-05-01,2,164,audi,std,four,sedan,4wd,front,99.4,...,8.0,115.0,5500.0,18,22,17450.0,13.055556,medium,0,1

In [28]:
numeric_cols = df_processed.select_dtypes(include="number").columns

In [29]:
print(numeric_cols.tolist())

['symboling', 'normalized-losses', 'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-size', 'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price', 'city-L/100km', 'diesel', 'gas']

In [30]:
col_min = df_processed[numeric_cols].min()
col_max = df_processed[numeric_cols].max()

denominator = (col_max - col_min).replace(0, 1)

df_processed[numeric_cols] = (
    df_processed[numeric_cols] - col_min
) / denominator

In [31]:
df_processed[numeric_cols].describe()

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
count,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000
mean,0.568159,0.298429,0.355598,0.494045,0.477697,0.497222,0.414145,0.248587,0.564780,0.565506,0.197767,0.258765,0.394965,0.338308,0.386489,0.199790,0.387638,0.099502,0.900498
std,0.250960,0.167520,0.176862,0.183913,0.179613,0.203985,0.200658,0.156781,0.191480,0.150515,0.250310,0.173893,0.195148,0.178423,0.179346,0.197083,0.190844,0.300083,0.300083
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.400000,0.188482,0.230321,0.383582,0.324786,0.350000,0.264158,0.139623,0.435714,0.495238,0.100000,0.102804,0.265306,0.166667,0.236842,0.066283,0.228704,0.000000,1.000000
50%,0.600000,0.298429,0.303207,0.479104,0.444444,0.525000,0.359193,0.222642,0.550000,0.580952,0.125000,0.219626,0.398110,0.305556,0.368421,0.127898,0.376157,0.000000,1.000000
75%,0.800000,0.376963,0.460641,0.632836,0.538462,0.641667,0.557797,0.301887,0.742857,0.638095,0.150000,0.317757,0.551020,0.472222,0.473684,0.282558,0.570175,0.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [32]:
df_processed[numeric_cols].head()

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
0,1.0,0.298429,0.058309,0.413433,0.324786,0.083333,0.411171,0.260377,0.664286,0.290476,0.1250,0.294393,0.346939,0.222222,0.289474,0.207959,0.481481,0.0,1.0
1,1.0,0.298429,0.058309,0.413433,0.324786,0.083333,0.411171,0.260377,0.664286,0.290476,0.1250,0.294393,0.346939,0.222222,0.289474,0.282558,0.481481,0.0,1.0
2,0.6,0.298429,0.230321,0.449254,0.444444,0.383333,0.517843,0.343396,0.100000,0.666667,0.1250,0.495327,0.346939,0.166667,0.263158,0.282558,0.570175,0.0,1.0
3,0.8,0.518325,0.384840,0.529851,0.504274,0.541667,0.329325,0.181132,0.464286,0.633333,0.1875,0.252336,0.551020,0.305556,0.368421,0.219254,0.376157,0.0,1.0
4,0.8,0.518325,0.373178,0.529851,0.521368,0.541667,0.518231,0.283019,0.464286,0.633333,0.0625,0.313084,0.551020,0.138889,0.157895,0.306142,0.621914,0.0,1.0

In [33]:
categorical_cols = df_processed.select_dtypes(
    include= ["object", "string", "category"]
).columns

print(categorical_cols.tolist())

['make', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'engine-type', 'num-of-cylinders', 'fuel-system', 'horsepower-binned']

In [36]:
df_processed = pd.get_dummies(
    df_processed,
    columns=categorical_cols,
    dtype=int
)

In [37]:
df_processed.head()

,transaction_date,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,...,fuel-system_2bbl,fuel-system_4bbl,fuel-system_idi,fuel-system_mfi,fuel-system_mpfi,fuel-system_spdi,fuel-system_spfi,horsepower-binned_high,horsepower-binned_low,horsepower-binned_medium
0,2025-01-01,1.0,0.298429,0.058309,0.413433,0.324786,0.083333,0.411171,0.260377,0.664286,...,0,0,0,0,1,0,0,0,0,1
1,2025-01-02,1.0,0.298429,0.058309,0.413433,0.324786,0.083333,0.411171,0.260377,0.664286,...,0,0,0,0,1,0,0,0,0,1
2,2025-03-01,0.6,0.298429,0.230321,0.449254,0.444444,0.383333,0.517843,0.343396,0.100000,...,0,0,0,0,1,0,0,0,0,1
3,2025-01-04,0.8,0.518325,0.384840,0.529851,0.504274,0.541667,0.329325,0.181132,0.464286,...,0,0,0,0,1,0,0,0,0,1
4,2025-05-01,0.8,0.518325,0.373178,0.529851,0.521368,0.541667,0.518231,0.283019,0.464286,...,0,0,0,0,1,0,0,0,0,1

In [38]:
df_processed.shape

(201, 81)

In [39]:
df_processed.columns

Index(['transaction_date', 'symboling', 'normalized-losses', 'wheel-base',
       'length', 'width', 'height', 'curb-weight', 'engine-size', 'bore',
       'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price', 'city-L/100km', 'diesel', 'gas',
       'make_alfa-romero', 'make_audi', 'make_bmw', 'make_chevrolet',
       'make_dodge', 'make_honda', 'make_isuzu', 'make_jaguar', 'make_mazda',
       'make_mercedes-benz', 'make_mercury', 'make_mitsubishi', 'make_nissan',
       'make_peugot', 'make_plymouth', 'make_porsche', 'make_renault',
       'make_saab', 'make_subaru', 'make_toyota', 'make_volkswagen',
       'make_volvo', 'aspiration_std', 'aspiration_turbo', 'num-of-doors_four',
       'num-of-doors_two', 'body-style_convertible', 'body-style_hardtop',
       'body-style_hatchback', 'body-style_sedan', 'body-style_wagon',
       'drive-wheels_4wd', 'drive-wheels_awd', 'drive-wheels_fwd',
       'drive-wheels_rwd', 'engine-location_front', 'engine-location_rear',
       'engine-type_dohc', 'engine-type_l', 'engine-type_ohc',
       'engine-type_ohcf', 'engine-type_ohcv', 'engine-type_rotor',
       'num-of-cylinders_eight', 'num-of-cylinders_five',
       'num-of-cylinders_four', 'num-of-cylinders_six',
       'num-of-cylinders_three', 'num-of-cylinders_twelve',
       'num-of-cylinders_two', 'fuel-system_1bbl', 'fuel-system_2bbl',
       'fuel-system_4bbl', 'fuel-system_idi', 'fuel-system_mfi',
       'fuel-system_mpfi', 'fuel-system_spdi', 'fuel-system_spfi',
       'horsepower-binned_high', 'horsepower-binned_low',
       'horsepower-binned_medium'],
      dtype='str')

In [40]:
df_processed.dtypes.value_counts()

int64             61
float64           19
datetime64[us]     1
Name: count, dtype: int64

In [44]:
df_processed.isnull().sum().sum()

np.int64(0)

In [45]:
df_processed.duplicated().sum()

np.int64(0)

In [47]:
df_processed[numeric_cols].agg(["min", "max"])

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [48]:
df_processed.dtypes.value_counts()

int64             61
float64           19
datetime64[us]     1
Name: count, dtype: int64

In [49]:
import os

os.makedirs("data/processed", exist_ok=True)

df_processed.to_csv(
    "data/processed/automobileEDA_processed.csv",
    index=False
)